### ISSUE TITLE
Max Voltage?

### ISSUE THREAD

**Issue by JohnGalt1717** [rin67630/Soft-Power2-MPPT#1]
Hi there, this looks really excellent!

Do you have any designs for say 600V input (Open)?

I'm considering building a board design for something like this that does 600VDC using GanFets and has a variable secondary boost/buck so that it will handle from say 48VDC to 600VDC on the solar side, and output to whatever voltage out you want up to 600VDC using a full bridge ZVS transformerless design.

**Comment by rin67630** [comment]
Hi am afraid anything above 60V is out of reach.
Beside that, even 60V DC is a dangerous voltage and can draw awful sparks, MUCH more than AC!

Nothing to tinker with. 
In many countries this is a voltage for professionals only with an accreditation. The risk is just to high...

My design is based on standard DC-DC converters, i don't know any module capable of handling more.

**Comment by JohnGalt1717** [comment]
OK. Thanks.

For the record for others, DC voltage is always SAFER (assuming no ripple) than AC voltage. That's why Extra low voltage states that 50VAC is safe and 120VDC is safe. And Low voltage is defined in every country in the world as 1000VAC and 1500VDC.

DC causes your muscles to clinch and then you can release.  AC pulses which causes continual clinching. It still sucks, but it's vastly safer. (and yes, over 120VDC can kill you if you get it wrong)

But the trend is to higher voltage MPPT of 450VDC and Higher which has much lower line loss for long runs and as long as you don't have shading or if you're using DC Optimizers, allows you to series more panels together without complex combiner boxes or losses because of having to stand on your head to get the same voltages in parallel.

I'd be happy to work with you to upgrade the design to handle higher voltages limited only by the fets that are chosen.

As an example, Monolithic power has a single chip low amperage synchronous buck that can be put on the battery side to power the ESP32 and a similar buck can be used for slightly higher amperage for 12V to drive GanFETS for the dual boost/bucks.  This would allow the input side to be only limited to the size of the voltage divider on the input side and the headroom of the FETS (gan up to about 800VDC max or 500VDC for the lower quality ones, and SiCs at 1100 or even 1700VDC if you really want to go high end)

The side effect of this is that you only have to build to 15-20 amps per MPPT.

And with proper configuration a battery of 400VDC is no big deal either.

**Comment by rin67630** [comment]
Dear John, 
Soft Power uses commercial DC/DC converters. These are limited in voltage, not the controller.
And please don't spread potential deadly wrong beliefs. 
High voltage DC is a killer.

**Comment by JohnGalt1717** [comment]
Ok, that's limiting. I guess this won't work.  I was hoping to avoid having to design my own firmware and synchronous buck/boosts for this, but ce la vie.

And no, I'm not spreading deadly wrong beliefs. You have a number of (common) incorrect beliefs about DC power. This is the truth if you look:

1. DC is safer Volt for Volt and amp for amp than AC.  You're more likely to survive the same voltage and amperage DC than AC. This is true at all voltage levels including but not limited to, mains voltage and low voltage.
2. The threshold for "safe" DC voltage is 120VDC versus 50VAC contrary to popular belief as long as the DC voltage has a ripple below 5%.
3. DC voltage is vastly less likely to arc than AC at a given voltage.

For reference I suggest you read: https://en.wikipedia.org/wiki/Extra-low_voltage
If you read up on why you'll understand that AC, because it moves from negative to positive causes a cyclical pattern of changing intensity that amplifies the effects both by creating multiple muscle spasms instead of a single one, and by creating a change relative to other surfaces and conductors around over time that increases the chances of arcing and other scenarios. 

I'm not guessing or making assertions without evidence. This is true in every country in the world with any standards at all.
